version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - 80:8000
    command: ["gunicorn", "-b", "0.0.0.0:8000", "project.wsgi"]
    env_file:
      - .env

  worker:
    build: .
    restart: always
    command: ["python", "manage.py", "download_and_save", "--loop"]
    env_file:
      - .env
